# Generated by Django 4.1.1 on 2022-10-05 17:20

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(9),
                            django.core.validators.MinValueValidator(1),
                        ]
                    ),
                ),
                ("date", models.TextField()),
                ("value", models.TextField()),
                ("cpf", models.TextField()),
                ("credit_card", models.TextField()),
                ("hour", models.TextField()),
                ("owner", models.TextField(max_length=14)),
                ("name", models.TextField(max_length=19)),
            ],
        ),
    ]
