# Generated by Django 4.1.1 on 2022-10-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cnab", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="cpf",
            field=models.TextField(max_length=11),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="credit_card",
            field=models.TextField(max_length=12),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.TextField(max_length=8),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="hour",
            field=models.TextField(max_length=6),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="value",
            field=models.TextField(max_length=10),
        ),
    ]
